/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package prime;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SerialSolutionTest {
    SerialSolution serialSolution = new SerialSolution();

    @Test
    public void testContainsNonPrime() {
        int[][] testCases = {
                {2, 3, 5, 7, 11, 13, 17},
                {4, 6, 8, 9, 10, 12, 14},
                {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
                {2, 3, 5, 7, 11, 13, 17, 19, 23, 29},
                {-1, -2, -3, -4, -5, -6, -7, -8, -9, -10}
        };
        boolean[] expectedResults = {
                false,
                true,
                true,
                false,
                true
        };
        for (int i = 0; i < testCases.length; i++) {
            assertEquals(expectedResults[i], serialSolution.containsNonPrime(testCases[i]));
        }
    }
}
