/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1_2_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StackTest {
    @Test void appHasAGreeting() {
        Stack classUnderTest = new Stack();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
