/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.peyuaa;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.ConcurrentModificationException;
import java.util.Deque;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;

/**
 * Tree class is acyclic oriented graph.
 *
 * @param <T> value type.
 */
public class Tree<T> implements Iterable<Tree.Node<T>> {
    static class Node<T> {
        private final T value;
        private Node<T> parent;
        private final List<Node<T>> children;

        public Node(T value) {
            this.value = value;
            this.children = new LinkedList<>();
        }

        private void addChild(Node<T> child) {
            child.parent = this;
            children.add(child);
        }

        private void deleteChild(Node<T> child) {
            children.remove(child);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Node<?> node = (Node<?>) o;
            return Objects.equals(value, node.value) && children.equals(node.children);
        }

        @Override
        public int hashCode() {
            return Objects.hash(value, children);
        }
    }

    private Node<T> root;
    private int modificationCounter = 0;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Tree<?> tree = (Tree<?>) o;
        return Objects.equals(root, tree.root);
    }

    @Override
    public int hashCode() {
        return Objects.hash(root);
    }

    @Override
    public Iterator<Node<T>> iterator() {
        return new BreadthFirstSearchIterator();
    }

    class BreadthFirstSearchIterator implements Iterator<Node<T>> {
        LinkedList<Node<T>> queue = new LinkedList<>();
        boolean isRootAdded = false;
        private final int modificationCounter;

        public BreadthFirstSearchIterator() {
            modificationCounter = Tree.this.modificationCounter;
        }

        @Override
        public boolean hasNext() {
            if (!isRootAdded) {
                queue.add(root);
                isRootAdded = true;
            }
            return queue.size() != 0;
        }

        @Override
        public Node<T> next() {
            if (modificationCounter != Tree.this.modificationCounter) {
                throw new ConcurrentModificationException();
            }
            Node<T> currentNode = queue.poll();
            queue.addAll(currentNode.children);
            return currentNode;
        }
    }

    class DepthFirstSearchIterator implements Iterator<Node<T>> {
        Deque<Node<T>> deque = new ArrayDeque<>();
        boolean isRootAdded = false;
        private final int modificationCounter;

        public DepthFirstSearchIterator() {
            modificationCounter = Tree.this.modificationCounter;
        }

        @Override
        public boolean hasNext() {
            if (!isRootAdded) {
                deque.offer(root);
                isRootAdded = true;
            }
            return !deque.isEmpty();
        }

        @Override
        public Node<T> next() {
            if (modificationCounter != Tree.this.modificationCounter) {
                throw new ConcurrentModificationException();
            }
            Node<T> currentNode = deque.pollLast();
            for (int i = currentNode.children.size() - 1; i >= 0; i--) {
                deque.offer(currentNode.children.get(i));
            }
            return currentNode;
        }
    }

    private Node<T> breadthFirstSearch(T value) {
        Iterator<Node<T>> bfsIterator = new BreadthFirstSearchIterator();

        while (bfsIterator.hasNext()) {
            Node<T> currentNode = bfsIterator.next();
            if (currentNode.value.equals(value)) {
                return currentNode;
            }
        }

        return null;
    }

    /**
     * Make node with specified value and set is as root in case root is not set yet.
     * In other case set that node root's child.
     *
     * @param value of the new node.
     * @return new added node.
     */
    public Node<T> add(T value) {
        Node<T> node = new Node<>(value);
        if (root == null) {
            root = node;
        } else {
            root.addChild(node);
        }
        modificationCounter++;
        return node;
    }

    /**
     * Add node as parent's child.
     *
     * @param parent of the new node.
     * @param value of the new node.
     * @return new node.
     */
    public Node<T> add(Node<T> parent, T value) {
        Node<T> node = new Node<>(value);
        parent.addChild(node);
        modificationCounter++;
        return node;
    }

    /**
     * Delete node with that value from tree.
     *
     * @param value to be deleted.
     */
    public void delete(T value) {
        Node<T> node = breadthFirstSearch(value);
        if (node != null) {
            delete(node);
        }
        modificationCounter++;
    }

    /**
     * Delete node.
     *
     * @param node to be deleted.
     */
    public void delete(Node<T> node) {
        if (node == root) {
            root = null;
        } else {
            node.parent.deleteChild(node);
        }
        modificationCounter++;
    }

    /**
     * Traverse a tree using breadth first search.
     *
     * @return traversal list.
     */
    public List<T> breadthFirstTraversal() {
        List<T> traverseResult = new ArrayList<>();

        Iterator<Node<T>> bfsIterator = new BreadthFirstSearchIterator();
        while (bfsIterator.hasNext()) {
            Node<T> currentNode = bfsIterator.next();
            traverseResult.add(currentNode.value);
        }
        return traverseResult;
    }

    /**
     * Traverse tree using depth first search.
     *
     * @return traversal list.
     */
    public List<T> depthFirstTraversal() {
        List<T> traverseResult = new ArrayList<>();

        Iterator<Node<T>> dfsIterator = new DepthFirstSearchIterator();
        while (dfsIterator.hasNext()) {
            Node<T> currentNode = dfsIterator.next();
            traverseResult.add(currentNode.value);
        }
        return traverseResult;
    }
}
