/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package prime;

import java.util.Arrays;

public class SerialSolution {
    public boolean containsNonPrime(int[] arr) {
        int max = 0;
        for (int k : arr) {
            max = Math.max(max, k);
        }

        if (max < 2) {
            return true;
        }

        boolean[] isPrime = new boolean[max + 1];
        Arrays.fill(isPrime, true);
        isPrime[0] = isPrime[1] = false;
        for (int i = 2; i <= Math.sqrt(max); i++) {
            if (isPrime[i]) {
                for (int j = i * i; j <= max; j += i) {
                    isPrime[j] = false;
                }
            }
        }
        for (int j : arr) {
            if (!isPrime[j]) return true;
        }
        return false;
    }

    public SerialSolution() {

    }
}
