/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package task_2_2_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PizzeriaTest {
    @Test void appHasAGreeting() {
        Pizzeria classUnderTest = new Pizzeria();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
