/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.peyuaa;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CalculatorTest {
    @Test void appHasAGreeting() {
        Calculator classUnderTest = new Calculator();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
