/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.peyuaa;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class CalculatorTest {
    @Test
    void plus() throws IOException {
        ByteArrayInputStream in = new ByteArrayInputStream("+ -7 5\n".getBytes());
        String expected = "-2.0\n";

        ByteArrayOutputStream actual = new ByteArrayOutputStream();
        final String utf8 = StandardCharsets.UTF_8.name();
        PrintStream ps = new PrintStream(actual, true, utf8);

        Calculator calculator = new Calculator(in, ps);
        calculator.startCalculator();

        Assertions.assertEquals(expected, actual.toString(utf8));

    }

    @Test
    void multiplication() throws IOException {
        ByteArrayInputStream in = new ByteArrayInputStream("* 17 9\n".getBytes());
        String expected = "153.0\n";

        ByteArrayOutputStream actual = new ByteArrayOutputStream();
        final String utf8 = StandardCharsets.UTF_8.name();
        PrintStream ps = new PrintStream(actual, true, utf8);

        Calculator calculator = new Calculator(in, ps);
        calculator.startCalculator();

        Assertions.assertEquals(expected, actual.toString(utf8));
    }

    @Test
    void division() throws IOException {
        ByteArrayInputStream in = new ByteArrayInputStream("/ 13 4\n".getBytes());
        String expected = "3.25\n";

        ByteArrayOutputStream actual = new ByteArrayOutputStream();
        final String utf8 = StandardCharsets.UTF_8.name();
        PrintStream ps = new PrintStream(actual, true, utf8);

        Calculator calculator = new Calculator(in, ps);
        calculator.startCalculator();

        Assertions.assertEquals(expected, actual.toString(utf8));
    }

    @Test
    void minus() throws IOException {
        ByteArrayInputStream in = new ByteArrayInputStream("- -91 9\n".getBytes());
        String expected = "-100.0\n";

        ByteArrayOutputStream actual = new ByteArrayOutputStream();
        final String utf8 = StandardCharsets.UTF_8.name();
        PrintStream ps = new PrintStream(actual, true, utf8);

        Calculator calculator = new Calculator(in, ps);
        calculator.startCalculator();

        Assertions.assertEquals(expected, actual.toString(utf8));
    }

}
