/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.peyuaa;

import java.util.HashMap;
import java.util.Map;

public class RecordBook {
    private final Map<String, Integer> grades = new HashMap<>();

    public double getGPA() {
        double sum = grades.values().stream().reduce(0, Integer::sum);
        return sum / grades.size();
    }
}