/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.peyuaa;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class NotebookTest {
    @Test
    void addNote() throws IOException, ParseException {
        try (
                PrintStream out = new PrintStream(new ByteArrayOutputStream());
                PrintStream err = new PrintStream(new ByteArrayOutputStream())
        ) {
            String fileName = "test.json";
            File file = new File(fileName);
            file.delete();

            GregorianCalendar calendar = (GregorianCalendar) GregorianCalendar.getInstance();
            calendar.clear();
            calendar.setTimeZone(TimeZone.getTimeZone("Asia/Novosibirsk"));
            calendar.set(2005, Calendar.APRIL, 13, 0, 0, 0);

            Notebook.DateTime mockedDateImpl = mock();
            when(mockedDateImpl.getDate()).thenReturn(calendar.getTime());

            String[] addNote = new String[]{"-add", "my note", "to be honest I hate notes"};
            Notebook.run(out, err, fileName, mockedDateImpl, addNote);

            String expected = "{\"notes\":[{\"title\":\"my note\",\"content\":\"to "
                    + "be honest I hate notes\",\"created\":1113325200000}]}";

            Assertions.assertEquals(expected, Files.readString(Paths.get(fileName)));

            file.delete();
        }
    }
}
