/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1_1_1;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

class HeapSortTest {
    private final HeapSort heapSort = new HeapSort();

    @Test
    void usualArray() {
        int[] expected = {1, 2, 3, 4, 5, 6};
        int[] got = {3, 4, 1, 2, 6, 5};

        heapSort.heapSort(got);
        assertArrayEquals(expected, got);
    }

    @Test
    void equalElements() {
        int[] expected = {1, 1, 1, 1, 1, 1};
        int[] got = {1, 1, 1, 1, 1, 1};

        heapSort.heapSort(got);
        assertArrayEquals(expected, got);
    }
}
