/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1_2_2;

public class Tree {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Tree().getGreeting());
    }
}
